[package]
name = "rust_enigma"
version = "0.1.0"
authors = ["Mateusz Fesz <mateuszfesz@wp.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
