[package]
name = "rust_enigma"
version = "0.1.0"
authors = ["Mateusz Fesz <mateuszfesz@wp.pl>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rust_enigma"
path = "src/bin.rs"

[dependencies]
